export enum SUPPORTED_VISUALIZATIONS_ENUM {
    CHOROPLETH_MAP,
    GRADUATED_CIRCULAR_MAP_1, //one variable
    GRADUATED_CIRCULAR_MAP_2, //two variables
    DOT_MAP,
    PIE_CHARTMAP,
    HEAT_MAP
}